// PARTYCONNECT ACTION CREATE

// GET PARTY CONNECT
export const GET_PARTYCONNECT_PROGRESS = "GET_PARTYCONNECT_PROGRESS"
export const GET_PARTYCONNECT_ERROR = "GET_PARTYCONNECT_ERROR"
export const GET_PARTYCONNECT_SUCCESS = "GET_PARTYCONNECT_SUCCESS"

// POST PARTY CONNECT
export const POST_PARTYCONNECT_PROGRESS = "POST_PARTYCONNECT_PROGRESS"
export const POST_PARTYCONNECT_ERROR = "POST_PARTYCONNECT_ERROR"
export const POST_PARTYCONNECT_SUCCESS = "POST_PARTYCONNECT_SUCCESS"

// DELETE PARTYCONNECT
export const DELETE_PARTYCONNECT_PROGRESS = "DELETE_PARTYCONNECT_PROGRESS";
export const DELETE_PARTYCONNECT_SUCCESS = "DELETE_PARTYCONNECT_SUCCESS";
export const DELETE_PARTYCONNECT_ERROR = "DELETE_PARTYCONNECT_ERROR";
